services:
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_ADDR: http://0.0.0.0:8200
    ports:
      - "8200:8200"
    command: server -dev
    volumes:
      - vault-data:/vault/file
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  vault-data:
